using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using AutopilotMonitor.Shared.Models;
using Newtonsoft.Json;

namespace AutopilotMonitor.Functions.Services
{
    /// <summary>
    /// Built-in IME log regex patterns loaded from embedded JSON resource.
    /// The JSON is generated by the CI combine script from individual files in rules/ime-log-patterns/.
    /// Delivered to the agent via the config API so patterns can be updated without agent rebuild.
    /// </summary>
    public static class BuiltInImeLogPatterns
    {
        /// <summary>
        /// IDs of the shipped patterns, resolved once. The ingest path filters the agent's
        /// <c>ime_pattern_hits</c> histogram against this set per batch — a device may only
        /// CLAIM an ID, and tenant custom IDs never reach the global statistics.
        /// </summary>
        public static readonly Lazy<HashSet<string>> BuiltInPatternIds = new(() =>
            new HashSet<string>(GetAll().Select(p => p.PatternId).Where(id => !string.IsNullOrEmpty(id)),
                StringComparer.OrdinalIgnoreCase));

        public static List<ImeLogPattern> GetAll()
        {
            var assembly = Assembly.GetExecutingAssembly();
            using var stream = assembly.GetManifestResourceStream(
                "AutopilotMonitor.Functions.Rules.ime-log-patterns.json");
            using var reader = new StreamReader(stream!);
            var json = reader.ReadToEnd();
            var wrapper = JsonConvert.DeserializeObject<RulesWrapper<ImeLogPattern>>(json);
            var patterns = wrapper?.Rules ?? new List<ImeLogPattern>();

            foreach (var pattern in patterns)
            {
                pattern.IsBuiltIn = true;
            }

            return patterns;
        }
    }
}
