using System.Collections.Generic;
using System.IO;
using System.Reflection;
using AutopilotMonitor.Shared.Models;
using Newtonsoft.Json;

namespace AutopilotMonitor.Functions.Services
{
    /// <summary>
    /// Built-in IME log regex patterns loaded from embedded JSON resource.
    /// The JSON is generated by the CI combine script from individual files in rules/ime-log-patterns/.
    /// Delivered to the agent via the config API so patterns can be updated without agent rebuild.
    /// </summary>
    public static class BuiltInImeLogPatterns
    {
        public static List<ImeLogPattern> GetAll()
        {
            var assembly = Assembly.GetExecutingAssembly();
            using var stream = assembly.GetManifestResourceStream(
                "AutopilotMonitor.Functions.Rules.ime-log-patterns.json");
            using var reader = new StreamReader(stream!);
            var json = reader.ReadToEnd();
            var wrapper = JsonConvert.DeserializeObject<RulesWrapper<ImeLogPattern>>(json);
            var patterns = wrapper?.Rules ?? new List<ImeLogPattern>();

            foreach (var pattern in patterns)
            {
                pattern.IsBuiltIn = true;
            }

            return patterns;
        }
    }
}
