import { validateBootstrapResponse } from "@/utils/bootstrapValidation";

export const runtime = "nodejs";

const BACKEND_API_URL =
  process.env.BACKEND_API_URL ?? "https://autopilotmonitor-api.azurewebsites.net";

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ code: string }> },
) {
  const { code } = await params;

  // Validate code format: 4-10 alphanumeric chars
  if (!/^[a-z0-9]{4,10}$/i.test(code)) {
    return errorScript("Invalid bootstrap code format.");
  }

  try {
    const validateRes = await fetch(
      `${BACKEND_API_URL}/api/bootstrap/validate/${encodeURIComponent(code)}`,
      { cache: "no-store" },
    );

    if (!validateRes.ok) {
      const body = await validateRes.json().catch(() => ({} as Record<string, string>));
      const msg =
        (body as Record<string, string>).message ??
        "Bootstrap code not found, expired, or revoked.";
      return errorScript(msg);
    }

    const data: unknown = await validateRes.json();
    const result = validateBootstrapResponse(data);
    if (!result.ok) {
      // Log the failure category only — never the offending value, to keep
      // attack payloads out of Application Insights dashboards/exports.
      console.warn(
        `[go/${code}] bootstrap response validation failed: ${result.reason}`,
      );
      return errorScript(
        "Bootstrap response failed validation. Contact support.",
      );
    }

    const script = generateOobeScript({
      tenantId: result.value.tenantId,
      bootstrapToken: result.value.token,
      agentDownloadUrl: result.value.agentDownloadUrl,
      expiresAt: result.value.expiresAt,
    });

    return new Response(script, {
      status: 200,
      headers: {
        "Content-Type": "text/plain; charset=utf-8",
        "Cache-Control": "no-store, no-cache",
        "X-Content-Type-Options": "nosniff",
      },
    });
  } catch {
    return errorScript(
      "Failed to validate bootstrap code. Please check your network connection and try again.",
    );
  }
}

function errorScript(message: string): Response {
  // Escape single quotes for PowerShell string
  const safeMsg = message.replace(/'/g, "''");
  const script = `Write-Host ''; Write-Host 'ERROR: ${safeMsg}' -ForegroundColor Red; Write-Host ''`;
  return new Response(script, {
    status: 200, // Return 200 so irm | iex works; the Write-Host will show the error
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "no-store, no-cache",
    },
  });
}

// SECURITY INVARIANT: All template parameters MUST come from
// validateBootstrapResponse() in @/utils/bootstrapValidation. The single-quoted
// PowerShell string literals below are the second line of defense against
// injection (single-quoted PS strings do NOT expand $(...), $var, or
// backticks). Do NOT change to double-quoted without re-reviewing the
// validator's character classes end-to-end.
function generateOobeScript(params: {
  tenantId: string;
  bootstrapToken: string;
  agentDownloadUrl: string;
  expiresAt: string;
}): string {
  const generatedAt = new Date().toISOString();
  return `#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Autopilot Monitor OOBE Bootstrap
    Generated: ${generatedAt}
    Expires:   ${params.expiresAt}

    This script was generated by the Autopilot Monitor platform.
    It installs the monitoring agent before Intune enrollment begins,
    enabling full session capture from the start of OOBE.
#>

$ErrorActionPreference = "Stop"

$AgentDownloadUrl = '${params.agentDownloadUrl}'
$AgentBasePath    = "$env:ProgramData\\AutopilotMonitor"
$AgentBinPath     = "$AgentBasePath\\Agent"
$AgentLogPath     = "$AgentBasePath\\Logs"
$LogFile          = "$AgentLogPath\\oobe_bootstrap.log"

# Create directories
New-Item -Path $AgentBasePath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
New-Item -Path $AgentBinPath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
New-Item -Path $AgentLogPath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] $Message"
    Write-Host $logMessage
    Add-Content -Path $LogFile -Value $logMessage -ErrorAction SilentlyContinue
}

try {
    Write-Log "===== Autopilot Monitor OOBE Bootstrap ====="
    Write-Log 'Bootstrap token expires: ${params.expiresAt}'

    # Check if agent is already installed
    $agentExePath = Join-Path $AgentBinPath "AutopilotMonitor.Agent.exe"
    if (Test-Path $agentExePath) {
        Write-Log "Agent already installed at $agentExePath -- skipping download"
    }
    else {
        # Download agent ZIP
        $zipPath = Join-Path $env:TEMP "AutopilotMonitor-Agent.zip"
        Write-Log "Downloading agent from $AgentDownloadUrl..."

        $maxDownloadAttempts = 3
        $downloadAttempt = 0

        do {
            $downloadAttempt++
            try {
                Write-Log "Download attempt $downloadAttempt/$maxDownloadAttempts"
                Invoke-WebRequest -Uri $AgentDownloadUrl -OutFile $zipPath -UseBasicParsing -TimeoutSec 60 -ErrorAction Stop
                Write-Log "Downloaded agent to $zipPath"
                break
            }
            catch {
                if ($downloadAttempt -ge $maxDownloadAttempts) { throw }
                $retryDelays = @(2, 4, 8)
                $delay = $retryDelays[$downloadAttempt - 1]
                Write-Log "Download failed (attempt $downloadAttempt): $($_.Exception.Message). Retrying in \${delay}s..."
                Start-Sleep -Seconds $delay
            }
        } while ($downloadAttempt -lt $maxDownloadAttempts)

        # Extract
        Expand-Archive -Path $zipPath -DestinationPath $AgentBinPath -Force
        Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
        Write-Log "Extracted agent to $AgentBinPath"

        if (-not (Test-Path $agentExePath)) {
            throw "Agent executable not found after extraction at $agentExePath"
        }
    }

    # Install agent with bootstrap token
    Write-Log "Installing agent with bootstrap token..."
    & $agentExePath --install --no-auth --bootstrap-token '${params.bootstrapToken}' --tenant-id '${params.tenantId}'
    $installExitCode = $LASTEXITCODE
    if ($installExitCode -ne 0) {
        throw "Agent install failed with exit code $installExitCode"
    }

    Write-Log "===== OOBE Bootstrap Complete ====="
    Write-Log "Agent is now monitoring. View progress at https://portal.autopilotmonitor.com"
    Write-Log ""
    Write-Log "The agent will:"
    Write-Log "  - Monitor enrollment from the very start"
    Write-Log "  - Switch to certificate auth after Intune enrollment"
    Write-Log "  - Self-destruct when enrollment completes"

    Write-Host ""
    Write-Host "Autopilot Monitor agent installed successfully!" -ForegroundColor Green
    Write-Host "View enrollment progress at https://portal.autopilotmonitor.com" -ForegroundColor Cyan
    Write-Host ""
}
catch {
    Write-Log "===== OOBE Bootstrap FAILED ====="
    Write-Log "ERROR: $($_.Exception.Message)"
    Write-Log "Stack trace: $($_.ScriptStackTrace)"
    Write-Host ""
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Check log file: $LogFile" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}
`;
}
