using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace AutopilotMonitor.Shared.Models.Notifications
{
    /// <summary>
    /// A named outbound notification channel (Teams / Slack / generic JSON webhook) configured
    /// per tenant. Stored as a JSON array in <c>TenantConfiguration.NotificationChannelsJson</c>
    /// (camelCase contract shared with the web UI).
    /// <para>
    /// Routing granularity: enrollment/SLA events are opted into per channel via the
    /// <c>NotifyOn*</c> toggles below; analyze rules reference a channel by <see cref="Id"/>
    /// (rule-level notify, see <c>RuleState.NotifyChannelIds</c>). A channel with all toggles
    /// off that is only referenced by rules acts as a dedicated "rules-only" channel.
    /// </para>
    /// </summary>
    public class NotificationChannel
    {
        /// <summary>
        /// Hard cap on channels per tenant. Excess entries are ignored at parse time so a
        /// hand-crafted oversized JSON blob cannot fan a single event out to arbitrarily
        /// many endpoints.
        /// </summary>
        public const int MaxChannelsPerTenant = 10;

        private static readonly JsonSerializerOptions JsonOptions = new()
        {
            PropertyNamingPolicy = JsonNamingPolicy.CamelCase,
            PropertyNameCaseInsensitive = true,
            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull,
        };

        /// <summary>
        /// Stable channel identifier (GUID string, generated by the web UI on creation).
        /// Rules reference channels by this id; secret restore-on-save matches by this id.
        /// </summary>
        public string Id { get; set; } = default!;

        /// <summary>Display name, e.g. "Service Desk" or "Team Slack".</summary>
        public string Name { get; set; } = default!;

        /// <summary>
        /// Provider type (int form of <see cref="WebhookProviderType"/>):
        /// 1=TeamsLegacyConnector, 2=TeamsWorkflowWebhook, 10=Slack, 20=GenericJson.
        /// </summary>
        public int ProviderType { get; set; }

        /// <summary>Webhook destination URL (secret — redacted for read-only viewers).</summary>
        public string? Url { get; set; }

        /// <summary>
        /// Custom HTTP request headers (JSON object: { "Header-Name": "value", ... }), applied
        /// only when <see cref="ProviderType"/> is GenericJson. Secret — redacted for readers.
        /// </summary>
        public string? CustomHeadersJson { get; set; }

        /// <summary>Master switch: a disabled channel never receives anything.</summary>
        public bool Enabled { get; set; } = true;

        // ── Per-channel event subscriptions (enrollment + SLA) ───────────────
        // Rule-fired alerts are NOT toggled here — rules target channels by id.

        /// <summary>Receive enrollment-started notifications (opt-in).</summary>
        public bool NotifyOnStart { get; set; }

        /// <summary>Receive enrollment-success / white-glove-success notifications.</summary>
        public bool NotifyOnSuccess { get; set; }

        /// <summary>Receive enrollment-failure / ESP-failure notifications.</summary>
        public bool NotifyOnFailure { get; set; }

        /// <summary>Receive hardware-whitelist-rejection notifications (opt-in).</summary>
        public bool NotifyOnHardwareRejection { get; set; }

        /// <summary>
        /// Receive SLA notifications (breach / resolved / consecutive failures). Which breach
        /// types are evaluated at all remains governed by the tenant-level <c>SlaNotifyOn*</c>
        /// flags — this toggle only decides whether THIS channel is a recipient.
        /// </summary>
        public bool NotifyOnSlaEvents { get; set; }

        /// <summary>
        /// Parses <see cref="CustomHeadersJson"/> into request headers for the generic-webhook
        /// dispatcher. Empty unless <see cref="ProviderType"/> is GenericJson. Never throws.
        /// </summary>
        public IReadOnlyDictionary<string, string> GetCustomHeaders()
        {
            if (ProviderType != (int)WebhookProviderType.GenericJson)
                return new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);

            return WebhookHeaderParser.Parse(CustomHeadersJson);
        }

        /// <summary>
        /// Deserializes a channel list from its JSON storage form. Fail-soft: null/blank/malformed
        /// input yields an empty list (dispatch then simply has no channels to send to). Entries
        /// without an id or with an unknown provider type are dropped; the list is capped at
        /// <see cref="MaxChannelsPerTenant"/>.
        /// </summary>
        public static List<NotificationChannel> ParseList(string? json)
        {
            var result = new List<NotificationChannel>();
            if (string.IsNullOrWhiteSpace(json))
                return result;

            List<NotificationChannel>? parsed;
            try
            {
                parsed = JsonSerializer.Deserialize<List<NotificationChannel>>(json!, JsonOptions);
            }
            catch (JsonException)
            {
                return result;
            }

            if (parsed == null)
                return result;

            foreach (var channel in parsed)
            {
                if (result.Count >= MaxChannelsPerTenant)
                    break;
                if (channel == null || string.IsNullOrWhiteSpace(channel.Id))
                    continue;
                if (!Enum.IsDefined(typeof(WebhookProviderType), channel.ProviderType)
                    || channel.ProviderType == (int)WebhookProviderType.None)
                    continue;

                result.Add(channel);
            }

            return result;
        }

        /// <summary>Serializes a channel list back to its JSON storage form (camelCase).</summary>
        public static string SerializeList(IEnumerable<NotificationChannel> channels)
            => JsonSerializer.Serialize(channels, JsonOptions);
    }
}
