#nullable enable
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;
using System.Text.Json;
using System.Text.Json.Serialization;
using AutopilotMonitor.Shared.Models;

namespace AutopilotMonitor.Shared.Services
{
    /// <summary>
    /// Single-source-of-truth lookup for Windows / MSI / Intune error codes. Loaded once
    /// from the embedded <c>Resources/error-codes.json</c> resource (schemaVersion 2,
    /// generated by <c>tools/error-codes/generate.mjs</c>) and exposed via dictionaries
    /// keyed by normalised code string (lowercase hex, e.g. <c>0x80070005</c>, or decimal MSI
    /// exit code, e.g. <c>1603</c>), by symbol and by enforcement state.
    /// <para>
    /// Mirror of <c>src/Web/autopilot-monitor-web/utils/errorCodeMap.ts</c> and the MCP
    /// server's <c>error-code-catalog.ts</c>; the JSON file is the authoritative copy.
    /// </para>
    /// </summary>
    public static class ErrorCodeCatalog
    {
        private const string ResourceName = "AutopilotMonitor.Shared.Resources.error-codes.json";
        private const int ExpectedSchemaVersion = 2;

        private static readonly Lazy<Loaded> _loaded = new Lazy<Loaded>(Load);

        /// <summary>All entries, keyed by normalised code string.</summary>
        public static IReadOnlyDictionary<string, ErrorCodeEntry> All => _loaded.Value.Entries;

        /// <summary>IME app enforcement states, keyed by their numeric string (<c>"1000"</c>).</summary>
        public static IReadOnlyDictionary<string, EnforcementStateEntry> EnforcementStates => _loaded.Value.EnforcementStates;

        /// <summary>
        /// Look up an entry for a raw code value. Accepts decimal strings (<c>"1603"</c>),
        /// hex strings (<c>"0x80070005"</c>, <c>"0X80070005"</c>) and signed-decimal HRESULTs
        /// (<c>"-2147024891"</c>). A <c>0x8007xxxx</c> value without a direct entry resolves
        /// through its low 16 bits to the decimal MSI entry. Returns <c>null</c> on a miss.
        /// </summary>
        public static ErrorCodeEntry? TryLookup(string? rawCode) => TryLookupDetailed(rawCode)?.Entry;

        /// <summary>
        /// Same resolution as <see cref="TryLookup"/>, plus the matched key and the
        /// <c>HRESULT_FROM_WIN32</c> derivation when one was applied.
        /// </summary>
        public static ErrorCodeLookupResult? TryLookupDetailed(string? rawCode)
        {
            if (string.IsNullOrWhiteSpace(rawCode)) return null;
            var raw = rawCode!.Trim();
            var all = All;

            // 1) Direct lookup (lower-cased, handles decimal keys and already-lowered hex)
            var lowered = raw.ToLowerInvariant();
            if (all.TryGetValue(lowered, out var direct))
                return new ErrorCodeLookupResult(direct, lowered, null);

            // 2) Hex input normalisation ("0X..." → "0x...", strip leading zeros, repad to 8)
            string? hexKey = null;
            if (raw.Length >= 2 && raw[0] == '0' && (raw[1] == 'x' || raw[1] == 'X'))
            {
                var body = raw.Substring(2).TrimStart('0').ToLowerInvariant();
                if (body.Length == 0) body = "0";
                if (body.Length <= 8) hexKey = "0x" + body.PadLeft(8, '0');
            }
            // 3) Signed-decimal HRESULT → unsigned hex  (e.g. -2147024891 → 0x80070005)
            else if (long.TryParse(raw, NumberStyles.Integer, CultureInfo.InvariantCulture, out var asLong) && asLong < 0 && asLong >= int.MinValue)
            {
                hexKey = "0x" + unchecked((uint)asLong).ToString("x8", CultureInfo.InvariantCulture);
            }

            if (hexKey == null) return null;
            if (all.TryGetValue(hexKey, out var hex))
                return new ErrorCodeLookupResult(hex, hexKey, null);

            // 4) HRESULT_FROM_WIN32 derivation: facility 7, no direct entry, low word ≠ 0
            //    (0x80070000 must not resolve to "Success"), decimal entry present.
            if (hexKey.StartsWith("0x8007", StringComparison.Ordinal))
            {
                var low = int.Parse(hexKey.Substring(6), NumberStyles.HexNumber, CultureInfo.InvariantCulture);
                if (low != 0)
                {
                    var decimalKey = low.ToString(CultureInfo.InvariantCulture);
                    if (all.TryGetValue(decimalKey, out var derived))
                        return new ErrorCodeLookupResult(derived, decimalKey, low);
                }
            }

            return null;
        }

        /// <summary>Entry by symbolic name (<c>ERROR_INSTALL_FAILURE</c>, <c>UnzipError</c>); case-insensitive.</summary>
        public static ErrorCodeLookupResult? TryLookupBySymbol(string? symbol)
        {
            if (string.IsNullOrWhiteSpace(symbol)) return null;
            return _loaded.Value.BySymbol.TryGetValue(symbol!.Trim(), out var key)
                ? new ErrorCodeLookupResult(All[key], key, null)
                : null;
        }

        /// <summary>Enforcement state by numeric value (<c>"1000"</c>, <c>1000</c>) or by name (<c>"Success"</c>); case-insensitive.</summary>
        public static EnforcementStateEntry? TryLookupEnforcementState(string? nameOrValue)
        {
            if (string.IsNullOrWhiteSpace(nameOrValue)) return null;
            var raw = nameOrValue!.Trim();
            if (EnforcementStates.TryGetValue(raw, out var byValue)) return byValue;
            return _loaded.Value.StatesByName.TryGetValue(raw, out var byName) ? byName : null;
        }

        private static Loaded Load()
        {
            var assembly = typeof(ErrorCodeCatalog).GetTypeInfo().Assembly;
            using var stream = assembly.GetManifestResourceStream(ResourceName);
            if (stream == null)
                throw new InvalidOperationException(
                    $"Embedded resource not found: {ResourceName}. Verify AutopilotMonitor.Shared.csproj " +
                    "includes Resources/error-codes.json as EmbeddedResource.");

            using var reader = new StreamReader(stream);
            var json = reader.ReadToEnd();

            var options = new JsonSerializerOptions
            {
                PropertyNameCaseInsensitive = true,
                Converters = { new JsonStringEnumConverter(JsonNamingPolicy.CamelCase, allowIntegerValues: false) },
            };

            var doc = JsonSerializer.Deserialize<CatalogFile>(json, options)
                ?? throw new InvalidOperationException("Failed to deserialize error-codes.json.");

            if (doc.SchemaVersion != ExpectedSchemaVersion)
                throw new InvalidOperationException($"error-codes.json has schemaVersion {doc.SchemaVersion}, expected {ExpectedSchemaVersion}.");
            if (doc.Entries == null)
                throw new InvalidOperationException("error-codes.json has no 'entries' property.");

            // Re-key everything to lower-case for case-insensitive lookups.
            var entries = new Dictionary<string, ErrorCodeEntry>(doc.Entries.Count, StringComparer.Ordinal);
            var bySymbol = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            foreach (var pair in doc.Entries)
            {
                var key = pair.Key.ToLowerInvariant();
                entries[key] = pair.Value;
                if (!string.IsNullOrEmpty(pair.Value.Symbol) && !bySymbol.ContainsKey(pair.Value.Symbol!))
                    bySymbol[pair.Value.Symbol!] = key;
            }

            var states = new Dictionary<string, EnforcementStateEntry>(StringComparer.Ordinal);
            var statesByName = new Dictionary<string, EnforcementStateEntry>(StringComparer.OrdinalIgnoreCase);
            foreach (var pair in doc.EnforcementStates ?? new Dictionary<string, EnforcementStateEntry>())
            {
                pair.Value.Value = pair.Key;
                states[pair.Key] = pair.Value;
                if (!string.IsNullOrEmpty(pair.Value.Name) && !statesByName.ContainsKey(pair.Value.Name))
                    statesByName[pair.Value.Name] = pair.Value;
            }

            return new Loaded(entries, bySymbol, states, statesByName);
        }

        private sealed class Loaded
        {
            public Loaded(
                IReadOnlyDictionary<string, ErrorCodeEntry> entries,
                IReadOnlyDictionary<string, string> bySymbol,
                IReadOnlyDictionary<string, EnforcementStateEntry> enforcementStates,
                IReadOnlyDictionary<string, EnforcementStateEntry> statesByName)
            {
                Entries = entries;
                BySymbol = bySymbol;
                EnforcementStates = enforcementStates;
                StatesByName = statesByName;
            }

            public IReadOnlyDictionary<string, ErrorCodeEntry> Entries { get; }
            public IReadOnlyDictionary<string, string> BySymbol { get; }
            public IReadOnlyDictionary<string, EnforcementStateEntry> EnforcementStates { get; }
            public IReadOnlyDictionary<string, EnforcementStateEntry> StatesByName { get; }
        }

        private sealed class CatalogFile
        {
            [JsonPropertyName("schemaVersion")] public int SchemaVersion { get; set; }
            [JsonPropertyName("description")] public string? Description { get; set; }
            [JsonPropertyName("entries")] public Dictionary<string, ErrorCodeEntry>? Entries { get; set; }
            [JsonPropertyName("enforcementStates")] public Dictionary<string, EnforcementStateEntry>? EnforcementStates { get; set; }
        }
    }
}
