#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Autopilot Monitor OOBE Bootstrap
    Generated: 2026-07-28T12:00:00.000Z
    Expires:   2026-08-01T12:00:00.000Z

    This script was generated by the Autopilot Monitor platform.
    It installs the monitoring agent before Intune enrollment begins,
    enabling full session capture from the start of OOBE.
#>

$ErrorActionPreference = "Stop"

$AgentDownloadUrl = 'https://download.autopilotmonitor.com/agent/AutopilotMonitor-Agent.zip'
$AgentBasePath    = "$env:ProgramData\AutopilotMonitor"
$AgentBinPath     = "$AgentBasePath\Agent"
$AgentLogPath     = "$AgentBasePath\Logs"
$LogFile          = "$AgentLogPath\oobe_bootstrap.log"

# Create directories
New-Item -Path $AgentBasePath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
New-Item -Path $AgentBinPath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
New-Item -Path $AgentLogPath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] $Message"
    Write-Host $logMessage
    Add-Content -Path $LogFile -Value $logMessage -ErrorAction SilentlyContinue
}

try {
    Write-Log "===== Autopilot Monitor OOBE Bootstrap ====="
    Write-Log 'Bootstrap token expires: 2026-08-01T12:00:00.000Z'

    # Check if agent is already installed
    $agentExePath = Join-Path $AgentBinPath "AutopilotMonitor.Agent.exe"
    if (Test-Path $agentExePath) {
        Write-Log "Agent already installed at $agentExePath -- skipping download"
    }
    else {
        # Download agent ZIP
        $zipPath = Join-Path $env:TEMP "AutopilotMonitor-Agent.zip"
        Write-Log "Downloading agent from $AgentDownloadUrl..."

        $maxDownloadAttempts = 3
        $downloadAttempt = 0

        do {
            $downloadAttempt++
            try {
                Write-Log "Download attempt $downloadAttempt/$maxDownloadAttempts"
                Invoke-WebRequest -Uri $AgentDownloadUrl -OutFile $zipPath -UseBasicParsing -TimeoutSec 60 -ErrorAction Stop
                Write-Log "Downloaded agent to $zipPath"
                break
            }
            catch {
                if ($downloadAttempt -ge $maxDownloadAttempts) { throw }
                $retryDelays = @(2, 4, 8)
                $delay = $retryDelays[$downloadAttempt - 1]
                Write-Log "Download failed (attempt $downloadAttempt): $($_.Exception.Message). Retrying in ${delay}s..."
                Start-Sleep -Seconds $delay
            }
        } while ($downloadAttempt -lt $maxDownloadAttempts)

        # Extract
        Expand-Archive -Path $zipPath -DestinationPath $AgentBinPath -Force
        Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
        Write-Log "Extracted agent to $AgentBinPath"

        if (-not (Test-Path $agentExePath)) {
            throw "Agent executable not found after extraction at $agentExePath"
        }
    }

    # Install agent with bootstrap token
    Write-Log "Installing agent with bootstrap token..."
    & $agentExePath --install --no-auth --bootstrap-token '22222222-2222-2222-2222-222222222222' --tenant-id '11111111-1111-1111-1111-111111111111'
    $installExitCode = $LASTEXITCODE
    if ($installExitCode -ne 0) {
        throw "Agent install failed with exit code $installExitCode"
    }

    Write-Log "===== OOBE Bootstrap Complete ====="
    Write-Log "Agent is now monitoring. View progress at https://portal.autopilotmonitor.com"
    Write-Log ""
    Write-Log "The agent will:"
    Write-Log "  - Monitor enrollment from the very start"
    Write-Log "  - Switch to certificate auth after Intune enrollment"
    Write-Log "  - Self-destruct when enrollment completes"

    Write-Host ""
    Write-Host "Autopilot Monitor agent installed successfully!" -ForegroundColor Green
    Write-Host "View enrollment progress at https://portal.autopilotmonitor.com" -ForegroundColor Cyan
    Write-Host ""
}
catch {
    Write-Log "===== OOBE Bootstrap FAILED ====="
    Write-Log "ERROR: $($_.Exception.Message)"
    Write-Log "Stack trace: $($_.ScriptStackTrace)"
    Write-Host ""
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Check log file: $LogFile" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}
