/**
 * Row catalog for the Tenant Config Report (admin/tenants/config-report).
 *
 * Both halves of the report are exhaustive over the generated wire types: `TENANT_FIELDS`
 * over every key of `TenantConfiguration` (GET config/{tenantId}) and `RUNTIME_FIELDS` /
 * `COLLECTOR_FIELDS` / `ANALYZER_FIELDS` over every key of `AgentConfigResponse` and its two
 * sub-objects (GET config/{tenantId}/effective-agent-config — the backend's own derivation,
 * nothing is re-computed here). A key is either rendered (a row with section and label) or
 * excluded with a reason — nothing can be silently forgotten: a new C# property forces the
 * wire-type regeneration (SharedManifestParityTests) and `tsc` then fails here until the key
 * is catalogued.
 *
 * The "custom" highlight compares a value against the C# initializer of the same property,
 * which the shared manifest carries as `defaults` (generated by the same test) — no
 * hand-copied default anywhere in this file.
 */
import { SHARED_MANIFEST } from "@/utils/shared-manifests.generated";
import type {
  AgentConfigResponse,
  AnalyzerConfiguration,
  CollectorConfiguration,
  TenantConfiguration,
} from "@/utils/wire-types.generated";

// ── Defaults from the manifest (compile-time complete over the wire types) ────

export const TENANT_DEFAULTS: Record<keyof TenantConfiguration, unknown> = SHARED_MANIFEST.tenantConfiguration.defaults;
export const RUNTIME_DEFAULTS: Record<keyof AgentConfigResponse, unknown> = SHARED_MANIFEST.agentConfig.responseDefaults;
export const COLLECTOR_DEFAULTS: Record<keyof CollectorConfiguration, unknown> = SHARED_MANIFEST.agentConfig.collectorDefaults;
export const ANALYZER_DEFAULTS: Record<keyof AnalyzerConfiguration, unknown> = SHARED_MANIFEST.agentConfig.analyzerDefaults;

// ── Row model ────────────────────────────────────────────────────────────────

/**
 * How a value is rendered. `secret` never shows the value, only whether one is set;
 * `count` shows the length of a list.
 */
export type RowKind = "value" | "date" | "masked" | "secret" | "count";

interface RowBase {
  label: string;
  kind?: RowKind;
  /** Informational rows (reasons, timestamps, identities, secrets) are never marked "custom". */
  informational?: true;
}

export interface TenantRow extends RowBase {
  section: TenantSection;
}

/** Which knob a runtime value is resolved from (AgentConfigResolver.Build). */
export type RuntimeSource = "tenant" | "global" | "entitlement" | "fixed";

export interface RuntimeRow extends RowBase {
  section: RuntimeSection;
  source: RuntimeSource;
}

export interface Excluded {
  excluded: string;
}

export const isExcluded = <T extends object>(spec: T | Excluded): spec is Excluded =>
  "excluded" in spec;

export const TENANT_SECTIONS = [
  "Tenant Status",
  "Plan & Billing",
  "Identity & App Homing",
  "Security & Validation",
  "Hardware Whitelist",
  "Data Management",
  "Agent Collectors",
  "Auth Circuit Breaker",
  "Agent Behavior",
  "Enrollment Summary",
  "Analyzers",
  "Webhooks",
  "SLA Targets",
  "Diagnostics",
  "Feature Flags (Global)",
] as const;
export type TenantSection = (typeof TENANT_SECTIONS)[number];

// ── Tenant configuration (left column) ───────────────────────────────────────

const HEADER = { excluded: "shown in the tenant header card" } as const;
const CHANNEL_BLOCK = { excluded: "rendered by the notification channel block (legacy fallback order)" } as const;

export const TENANT_FIELDS: Record<keyof TenantConfiguration, TenantRow | Excluded> = {
  tenantId: HEADER,
  domainName: HEADER,
  lastUpdated: HEADER,
  updatedBy: HEADER,

  // Tenant Status
  disabled: { section: "Tenant Status", label: "Disabled" },
  disabledReason: { section: "Tenant Status", label: "Disabled Reason", informational: true },
  disabledUntil: { section: "Tenant Status", label: "Disabled Until", kind: "date", informational: true },
  mcpDisabled: { section: "Tenant Status", label: "MCP Disabled" },
  mcpDisabledReason: { section: "Tenant Status", label: "MCP Disabled Reason", informational: true },
  onboardedAt: { section: "Tenant Status", label: "Onboarded At", kind: "date", informational: true },
  onboardedBy: { section: "Tenant Status", label: "Onboarded By", informational: true },
  contactEmail: { section: "Tenant Status", label: "Contact Email", informational: true },
  companyName: { section: "Tenant Status", label: "Company", informational: true },

  // Plan & Billing (stored values; the effective edition comes from feature-flags, header card)
  planTier: { section: "Plan & Billing", label: "Plan Tier (stored)" },
  trialExpiresUtc: { section: "Plan & Billing", label: "Trial Expires", kind: "date", informational: true },
  trialStartedUtc: { section: "Plan & Billing", label: "Trial Started", kind: "date", informational: true },
  trialGrantedBy: { section: "Plan & Billing", label: "Trial Granted By", informational: true },
  trialConsumed: { section: "Plan & Billing", label: "Trial Consumed" },
  proDowngradedUtc: { section: "Plan & Billing", label: "Pro Downgraded At", kind: "date", informational: true },
  payingCustomer: { section: "Plan & Billing", label: "Paying Customer" },
  maxDelegatedTenantsOverride: { section: "Plan & Billing", label: "Delegated Tenant Slots (override)" },
  mcpUsagePlanOverride: { section: "Plan & Billing", label: "MCP Usage Plan (override)" },
  managedByProTenantId: { section: "Plan & Billing", label: "Managed By Pro Tenant" },

  // Identity & App Homing
  homedAppClientId: { section: "Identity & App Homing", label: "Homed App Client ID", informational: true },
  lastAuthClientId: { section: "Identity & App Homing", label: "Last Auth Client ID", informational: true },
  lastAuthClientIdSince: { section: "Identity & App Homing", label: "Last Auth Client ID Since", kind: "date", informational: true },
  entraAppRolesEnabled: { section: "Identity & App Homing", label: "Entra App Roles Enabled" },

  // Security & Validation
  validateAutopilotDevice: { section: "Security & Validation", label: "Validate Autopilot Device" },
  validateCorporateIdentifier: { section: "Security & Validation", label: "Validate Corporate Identifier" },
  validateDeviceAssociation: { section: "Security & Validation", label: "Validate Device Association" },
  validateCloudPcDevice: { section: "Security & Validation", label: "Validate Cloud PC Device" },
  validateIntuneDeviceBinding: { section: "Security & Validation", label: "Validate Intune Device Binding" },
  allowInsecureAgentRequests: { section: "Security & Validation", label: "Allow Insecure Agent Requests" },
  customRateLimitRequestsPerMinute: { section: "Security & Validation", label: "Device API Rate Limit Override" },
  customUserRateLimitRequestsPerMinute: { section: "Security & Validation", label: "MCP & Integrations API Rate Limit Override" },

  // Hardware Whitelist
  manufacturerWhitelist: { section: "Hardware Whitelist", label: "Manufacturers" },
  modelWhitelist: { section: "Hardware Whitelist", label: "Models" },
  webhookNotifyOnHardwareRejection: { section: "Hardware Whitelist", label: "Notify On Hardware Rejection" },

  // Data Management
  dataRetentionDays: { section: "Data Management", label: "Data Retention (days)" },
  sessionTimeoutHours: { section: "Data Management", label: "Session Timeout (hours)" },
  sessionGraceHours: { section: "Data Management", label: "Session Grace (hours)" },
  absoluteMaxSessionHours: { section: "Data Management", label: "Absolute Max Session (hours)" },
  maxNdjsonPayloadSizeMB: { section: "Data Management", label: "Max NDJSON Payload (MB)" },

  // Agent Collectors
  enablePerformanceCollector: { section: "Agent Collectors", label: "Performance Collector" },
  performanceCollectorIntervalSeconds: { section: "Agent Collectors", label: "Perf. Interval (sec)" },
  helloWaitTimeoutSeconds: { section: "Agent Collectors", label: "Hello Wait Timeout (sec)" },

  // Auth Circuit Breaker
  maxAuthFailures: { section: "Auth Circuit Breaker", label: "Max Auth Failures" },
  authFailureTimeoutMinutes: { section: "Auth Circuit Breaker", label: "Auth Failure Timeout (min)" },
  agentMaxLifetimeMinutes: { section: "Auth Circuit Breaker", label: "Agent Max Lifetime (min)" },

  // Agent Behavior
  selfDestructOnComplete: { section: "Agent Behavior", label: "Self-Destruct On Complete" },
  keepLogFile: { section: "Agent Behavior", label: "Keep Log File" },
  rebootOnComplete: { section: "Agent Behavior", label: "Reboot On Complete" },
  rebootDelaySeconds: { section: "Agent Behavior", label: "Reboot Delay (sec)" },
  enableGeoLocation: { section: "Agent Behavior", label: "Geo-Location" },
  enableTimezoneAutoSet: { section: "Agent Behavior", label: "Timezone Auto-Set" },
  enableDoGroupIdAutoSet: { section: "Agent Behavior", label: "DO GroupId Auto-Set" },
  ntpServer: { section: "Agent Behavior", label: "NTP Server" },
  keepAwakeDuringUserEsp: { section: "Agent Behavior", label: "Keep Awake During User ESP" },
  enableImeMatchLog: { section: "Agent Behavior", label: "IME Match Log" },
  enableGatherRuleDebugLog: { section: "Agent Behavior", label: "Gather Rule Debug Log" },
  enableEspContinueAnywayObservation: { section: "Agent Behavior", label: "Continue-Anyway Observation" },
  logLevel: { section: "Agent Behavior", label: "Log Level" },
  maxBatchSize: { section: "Agent Behavior", label: "Max Batch Size" },
  showScriptOutput: { section: "Agent Behavior", label: "Show Script Output" },
  sendTraceEvents: { section: "Agent Behavior", label: "Send Trace Events" },

  // Enrollment Summary
  showEnrollmentSummary: { section: "Enrollment Summary", label: "Show Summary" },
  enrollmentSummaryTimeoutSeconds: { section: "Enrollment Summary", label: "Timeout (sec)" },
  enrollmentSummaryBrandingImageUrl: { section: "Enrollment Summary", label: "Branding Image URL" },
  enrollmentSummaryLaunchRetrySeconds: { section: "Enrollment Summary", label: "Launch Retry (sec)" },

  // Analyzers
  enableLocalAdminAnalyzer: { section: "Analyzers", label: "Local Admin Analyzer" },
  localAdminAllowedAccountsJson: { section: "Analyzers", label: "Allowed Local Admin Accounts" },
  enableSoftwareInventoryAnalyzer: { section: "Analyzers", label: "Software Inventory Analyzer" },
  enableIntegrityBypassAnalyzer: { section: "Analyzers", label: "Integrity Bypass Analyzer" },
  enableConsoleBypassDetection: { section: "Analyzers", label: "Console Bypass Detection" },
  enableRealmJoinWatcher: { section: "Analyzers", label: "Realm Join Watcher" },

  // Webhooks — channel list plus the legacy single-webhook fields it falls back to
  notificationChannelsJson: CHANNEL_BLOCK,
  webhookProviderType: CHANNEL_BLOCK,
  webhookUrl: CHANNEL_BLOCK,
  webhookNotifyOnSuccess: CHANNEL_BLOCK,
  webhookNotifyOnFailure: CHANNEL_BLOCK,
  webhookNotifyOnStart: CHANNEL_BLOCK,
  teamsWebhookUrl: CHANNEL_BLOCK,
  teamsNotifyOnSuccess: CHANNEL_BLOCK,
  teamsNotifyOnFailure: CHANNEL_BLOCK,
  teamsNotifyOnStart: CHANNEL_BLOCK,
  webhookCustomHeadersJson: { section: "Webhooks", label: "Custom Headers", kind: "secret", informational: true },

  // SLA Targets
  slaTargetSuccessRate: { section: "SLA Targets", label: "Target Success Rate (%)" },
  slaTargetMaxDurationMinutes: { section: "SLA Targets", label: "Target Max Duration (min)" },
  slaTargetAppInstallSuccessRate: { section: "SLA Targets", label: "Target App Install Success Rate (%)" },
  slaNotifyOnSuccessRateBreach: { section: "SLA Targets", label: "Notify On Success Rate Breach" },
  slaSuccessRateNotifyThreshold: { section: "SLA Targets", label: "Success Rate Notify Threshold (%)" },
  slaNotifyOnDurationBreach: { section: "SLA Targets", label: "Notify On Duration Breach" },
  slaNotifyOnAppInstallBreach: { section: "SLA Targets", label: "Notify On App Install Breach" },
  slaNotifyOnConsecutiveFailures: { section: "SLA Targets", label: "Notify On Consecutive Failures" },
  slaConsecutiveFailureThreshold: { section: "SLA Targets", label: "Consecutive Failure Threshold" },

  // Diagnostics
  diagnosticsUploadMode: { section: "Diagnostics", label: "Upload Mode" },
  diagnosticsUploadDestination: { section: "Diagnostics", label: "Upload Destination" },
  diagnosticsBlobSasUrl: { section: "Diagnostics", label: "Blob SAS URL", kind: "masked", informational: true },
  diagnosticsLogPathsJson: { section: "Diagnostics", label: "Custom Log Paths" },

  // Feature Flags (Global)
  bootstrapTokenEnabled: { section: "Feature Flags (Global)", label: "Bootstrap Token Enabled" },
  unrestrictedModeEnabled: { section: "Feature Flags (Global)", label: "Unrestricted Mode Enabled (GA gate)" },
  unrestrictedMode: { section: "Feature Flags (Global)", label: "Unrestricted Mode (tenant toggle)" },
};

// ── Runtime parameters (right column) ────────────────────────────────────────

export const RUNTIME_SECTIONS = [
  "Upload & Batching",
  "Agent Behavior",
  "Auth Circuit Breaker",
  "Enrollment Summary",
  "Collectors",
  "Collector Internals",
  "Diagnostics",
  "Analyzers",
  "Catalogs & Integrity",
] as const;
export type RuntimeSection = (typeof RUNTIME_SECTIONS)[number];

/** Sections rendered collapsed by default (agent class defaults, rarely relevant). */
export const RUNTIME_SECTIONS_COLLAPSED: ReadonlySet<RuntimeSection> = new Set<RuntimeSection>(["Collector Internals"]);

const PER_DEVICE = { excluded: "per-device kill verdict, only on the agent channel" } as const;
const SUB_OBJECT = { excluded: "sub-object, catalogued separately" } as const;

/** Agent class default, neither tenant- nor operator-tunable — shown once, collapsed. */
const internal = (label: string): RuntimeRow => ({ section: "Collector Internals", label, source: "fixed" });

export const RUNTIME_FIELDS: Record<keyof AgentConfigResponse, RuntimeRow | Excluded> = {
  configVersion: { section: "Catalogs & Integrity", label: "Config Version", source: "fixed", informational: true },
  uploadIntervalSeconds: { section: "Upload & Batching", label: "Upload Interval (sec)", source: "fixed" },
  maxBatchSize: { section: "Upload & Batching", label: "Max Batch Size", source: "tenant" },

  selfDestructOnComplete: { section: "Agent Behavior", label: "Self-Destruct", source: "tenant" },
  keepLogFile: { section: "Agent Behavior", label: "Keep Log File", source: "tenant" },
  rebootOnComplete: { section: "Agent Behavior", label: "Reboot On Complete", source: "tenant" },
  rebootDelaySeconds: { section: "Agent Behavior", label: "Reboot Delay (sec)", source: "tenant" },
  enableGeoLocation: { section: "Agent Behavior", label: "Geo-Location", source: "tenant" },
  enableTimezoneAutoSet: { section: "Agent Behavior", label: "Timezone Auto-Set", source: "tenant" },
  enableDoGroupIdAutoSet: { section: "Agent Behavior", label: "DO GroupId Auto-Set", source: "tenant" },
  ntpServer: { section: "Agent Behavior", label: "NTP Server", source: "tenant" },
  enableImeMatchLog: { section: "Agent Behavior", label: "IME Match Log", source: "tenant" },
  enableGatherRuleDebugLog: { section: "Agent Behavior", label: "Gather Rule Debug Log", source: "tenant" },
  enableEspContinueAnywayObservation: { section: "Agent Behavior", label: "Continue-Anyway Observation", source: "tenant" },
  logLevel: { section: "Agent Behavior", label: "Log Level", source: "tenant" },
  sendTraceEvents: { section: "Agent Behavior", label: "Send Trace Events", source: "tenant" },
  // TenantEntitlementService.IsUnrestrictedModeActive = edition entitlement && GA gate && tenant toggle.
  unrestrictedMode: { section: "Agent Behavior", label: "Unrestricted Mode (effective)", source: "entitlement" },
  allowAgentDowngrade: { section: "Agent Behavior", label: "Allow Agent Downgrade", source: "global" },

  maxAuthFailures: { section: "Auth Circuit Breaker", label: "Max Auth Failures", source: "tenant" },
  authFailureTimeoutMinutes: { section: "Auth Circuit Breaker", label: "Auth Failure Timeout (min)", source: "tenant" },

  showEnrollmentSummary: { section: "Enrollment Summary", label: "Show Summary", source: "tenant" },
  enrollmentSummaryTimeoutSeconds: { section: "Enrollment Summary", label: "Timeout (sec)", source: "tenant" },
  enrollmentSummaryBrandingImageUrl: { section: "Enrollment Summary", label: "Branding Image URL", source: "tenant" },
  enrollmentSummaryLaunchRetrySeconds: { section: "Enrollment Summary", label: "Launch Retry (sec)", source: "tenant" },

  diagnosticsUploadEnabled: { section: "Diagnostics", label: "Upload Enabled", source: "tenant" },
  diagnosticsUploadMode: { section: "Diagnostics", label: "Upload Mode", source: "tenant" },
  diagnosticsLogPaths: { section: "Diagnostics", label: "Log Paths (global + tenant)", source: "global", kind: "count" },

  collectors: SUB_OBJECT,
  analyzers: SUB_OBJECT,

  gatherRules: { section: "Catalogs & Integrity", label: "Active Gather Rules", source: "tenant", kind: "count", informational: true },
  imeLogPatterns: { section: "Catalogs & Integrity", label: "Active IME Log Patterns", source: "tenant", kind: "count", informational: true },
  whiteGloveSealingPatternIds: { section: "Catalogs & Integrity", label: "White Glove Sealing Pattern IDs", source: "global", informational: true },
  latestAgentSha256: { section: "Catalogs & Integrity", label: "Latest Agent ZIP SHA-256", source: "global", informational: true },
  latestAgentExeSha256: { section: "Catalogs & Integrity", label: "Latest Agent EXE SHA-256", source: "global", informational: true },
  migrateToApiBaseUrl: { section: "Catalogs & Integrity", label: "Migrate To API Base URL", source: "global" },

  deviceBlocked: PER_DEVICE,
  deviceKillSignal: PER_DEVICE,
  unblockAt: PER_DEVICE,
};

export const COLLECTOR_FIELDS: Record<keyof CollectorConfiguration, RuntimeRow | Excluded> = {
  enablePerformanceCollector: { section: "Collectors", label: "Performance Collector", source: "tenant" },
  performanceIntervalSeconds: { section: "Collectors", label: "Perf. Interval (sec)", source: "tenant" },
  collectorIdleTimeoutMinutes: { section: "Collectors", label: "Idle Timeout (min)", source: "global" },
  desktopDetectorNoCandidateTimeoutMinutes: { section: "Collectors", label: "Desktop Detector No-Candidate Timeout (min)", source: "global" },
  enableAgentSelfMetrics: { section: "Collectors", label: "Agent Self-Metrics", source: "fixed" },
  agentSelfMetricsIntervalSeconds: { section: "Collectors", label: "Self-Metrics Interval (sec)", source: "fixed" },
  helloWaitTimeoutSeconds: { section: "Collectors", label: "Hello Wait Timeout (sec)", source: "tenant" },
  agentMaxLifetimeMinutes: { section: "Collectors", label: "Agent Max Lifetime (min)", source: "tenant" },
  modernDeploymentHarmlessEventIds: { section: "Collectors", label: "Modern Deployment Harmless Event IDs", source: "global" },
  enableDeliveryOptimizationCollector: internal("Delivery Optimization Collector"),
  deliveryOptimizationIntervalSeconds: internal("DO Interval (sec)"),
  enableOfficeInstallDetector: internal("Office Install Detector"),
  officeInstallSettleSeconds: internal("Office Install Settle (sec)"),
  enablePowerStateWatcher: internal("Power State Watcher"),
  stallProbeEnabled: internal("Stall Probe"),
  stallProbeThresholdsMinutes: internal("Stall Probe Thresholds (min)"),
  stallProbeTraceIndices: internal("Stall Probe Trace Indices"),
  stallProbeSources: internal("Stall Probe Sources"),
  sessionStalledAfterProbeIndex: internal("Session Stalled After Probe Index"),
  modernDeploymentWatcherEnabled: internal("Modern Deployment Watcher"),
  modernDeploymentLogLevelMax: internal("Modern Deployment Log Level Max"),
  modernDeploymentBackfillEnabled: internal("Modern Deployment Backfill"),
  modernDeploymentBackfillLookbackMinutes: internal("Modern Deployment Backfill Lookback (min)"),
  windowsUpdateWatcherEnabled: internal("Windows Update Watcher"),
  windowsUpdateTargetedEventIds: internal("Windows Update Targeted Event IDs"),
  windowsUpdateBackfillLookbackMinutes: internal("Windows Update Backfill Lookback (min)"),
  windowsUpdateChannelCensusEnabled: internal("Windows Update Channel Census"),
  mdmRebootPolicyWatcherEnabled: internal("MDM Reboot Policy Watcher"),
  mdmRebootPolicyBackfillLookbackMinutes: internal("MDM Reboot Policy Backfill Lookback (min)"),
  enableSystemTimelineWatcher: internal("System Timeline Watcher"),
  systemEventBackfillLookbackMinutes: internal("System Event Backfill Lookback (min)"),
};

export const ANALYZER_FIELDS: Record<keyof AnalyzerConfiguration, RuntimeRow | Excluded> = {
  enableLocalAdminAnalyzer: { section: "Analyzers", label: "Local Admin Analyzer", source: "tenant" },
  localAdminAllowedAccounts: { section: "Analyzers", label: "Allowed Local Admin Accounts", source: "tenant" },
  enableSoftwareInventoryAnalyzer: { section: "Analyzers", label: "Software Inventory Analyzer", source: "tenant" },
  enableIntegrityBypassAnalyzer: { section: "Analyzers", label: "Integrity Bypass Analyzer", source: "tenant" },
  enableRealmJoinWatcher: { section: "Analyzers", label: "Realm Join Watcher", source: "tenant" },
  keepAwakeDuringUserEsp: { section: "Analyzers", label: "Keep Awake During User ESP", source: "tenant" },
  enableConsoleBypassDetection: { section: "Analyzers", label: "Console Bypass Detection", source: "tenant" },
};

// ── Ordered views for rendering ──────────────────────────────────────────────

/** One rendered row: where its value and default come from, resolved against a response. */
export interface CataloguedRuntimeRow {
  key: string;
  row: RuntimeRow;
  value: (r: AgentConfigResponse) => unknown;
  default: unknown;
}

export interface CataloguedTenantRow {
  key: keyof TenantConfiguration;
  row: TenantRow;
  default: unknown;
}

function tenantRows(): Array<{ section: TenantSection; rows: CataloguedTenantRow[] }> {
  const bySection = new Map<TenantSection, CataloguedTenantRow[]>(TENANT_SECTIONS.map((s) => [s, []]));
  for (const [key, spec] of Object.entries(TENANT_FIELDS) as Array<[keyof TenantConfiguration, TenantRow | Excluded]>) {
    if (isExcluded(spec)) continue;
    bySection.get(spec.section)!.push({ key, row: spec, default: TENANT_DEFAULTS[key] });
  }
  return TENANT_SECTIONS.map((section) => ({ section, rows: bySection.get(section)! }));
}

function runtimeRows(): Array<{ section: RuntimeSection; rows: CataloguedRuntimeRow[] }> {
  const bySection = new Map<RuntimeSection, CataloguedRuntimeRow[]>(RUNTIME_SECTIONS.map((s) => [s, []]));
  const add = (key: string, spec: RuntimeRow | Excluded, value: (r: AgentConfigResponse) => unknown, def: unknown) => {
    if (isExcluded(spec)) return;
    bySection.get(spec.section)!.push({ key, row: spec, value, default: def });
  };
  for (const [key, spec] of Object.entries(RUNTIME_FIELDS) as Array<[keyof AgentConfigResponse, RuntimeRow | Excluded]>) {
    add(key, spec, (r) => r[key], RUNTIME_DEFAULTS[key]);
  }
  for (const [key, spec] of Object.entries(COLLECTOR_FIELDS) as Array<[keyof CollectorConfiguration, RuntimeRow | Excluded]>) {
    add(`collectors.${key}`, spec, (r) => r.collectors?.[key], COLLECTOR_DEFAULTS[key]);
  }
  for (const [key, spec] of Object.entries(ANALYZER_FIELDS) as Array<[keyof AnalyzerConfiguration, RuntimeRow | Excluded]>) {
    add(`analyzers.${key}`, spec, (r) => r.analyzers?.[key], ANALYZER_DEFAULTS[key]);
  }
  return RUNTIME_SECTIONS.map((section) => ({ section, rows: bySection.get(section)! }));
}

export const TENANT_REPORT_SECTIONS = tenantRows();
export const RUNTIME_REPORT_SECTIONS = runtimeRows();

/**
 * Value equality for the "custom" highlight: null, undefined and the empty string are one
 * "unset" value (the table row stores a cleared string as "", the C# initializer is null),
 * arrays compare by content.
 */
export function isNonDefault(value: unknown, def: unknown): boolean {
  const isNil = (v: unknown) => v === null || v === undefined || v === "";
  const valueNil = isNil(value);
  const defNil = isNil(def);
  if (valueNil || defNil) return valueNil !== defNil;
  if (Array.isArray(value) && Array.isArray(def)) {
    return value.length !== def.length || value.some((v, i) => v !== def[i]);
  }
  return value !== def;
}
