#nullable enable
using System.Collections.Generic;
using System.Linq;
using System.Text.RegularExpressions;
using AutopilotMonitor.Shared.Models;
using AutopilotMonitor.Shared.Services;
using Xunit;

namespace AutopilotMonitor.Functions.Tests.Shared;

/// <summary>
/// Pins the schemaVersion-2 catalog contract (generated by tools/error-codes/generate.mjs):
/// key/source/category vocabulary, the HRESULT_FROM_WIN32 derivation, the symbol and
/// enforcement-state indexes, and the handful of entries product code and rules rely on.
/// </summary>
public sealed class ErrorCodeCatalogTests
{
    private static readonly Regex KeyPattern = new(@"^(0x[0-9a-f]{8}|\d+)$", RegexOptions.Compiled);
    private static readonly Regex SourcePattern = new(
        @"^(msdoc:https://learn\.microsoft\.com/\S+|ime:\d+(\.\d+)+|winerror\.h|rule:[A-Z]+-[A-Z]+-\d{3}|legacy-catalog-v1)$",
        RegexOptions.Compiled);
    private static readonly HashSet<string> Categories = new()
    {
        "msi", "win32", "com", "appx", "windows-update", "cbs", "intune-win32", "intune-mobile",
        "mdm-enrollment", "autopilot", "entra-join", "delivery-optimization",
    };

    [Fact]
    public void All_loads_entries_from_embedded_resource()
    {
        var all = ErrorCodeCatalog.All;

        Assert.NotEmpty(all);
        Assert.True(all.Count > 400, $"Expected the v2 catalog to have >400 entries, got {all.Count}");
        Assert.True(ErrorCodeCatalog.EnforcementStates.Count > 40, "Expected the IME enforcement states");
    }

    [Fact]
    public void Every_entry_matches_the_schema_v2_vocabulary()
    {
        foreach (var (key, entry) in ErrorCodeCatalog.All)
        {
            Assert.Matches(KeyPattern, key);
            Assert.False(string.IsNullOrWhiteSpace(entry.Description), $"{key}: empty description");
            Assert.True(Categories.Contains(entry.Category), $"{key}: category '{entry.Category}' outside the catalog vocabulary");
            Assert.Matches(SourcePattern, entry.Source);
            if (entry.Symbol != null) Assert.Matches("^[A-Za-z][A-Za-z0-9_]{2,}$", entry.Symbol);
        }

        // Decimal keys are MSI exit codes only; every other decimal exit code is installer-defined.
        foreach (var key in ErrorCodeCatalog.All.Keys.Where(k => !k.StartsWith("0x")))
        {
            var n = int.Parse(key);
            Assert.True(n == 0 || (n >= 1601 && n <= 1654) || n == 3010, $"decimal key {key} outside the MSI range");
        }
    }

    [Fact]
    public void Symbols_are_unique()
    {
        var duplicates = ErrorCodeCatalog.All.Values
            .Where(e => e.Symbol != null)
            .GroupBy(e => e.Symbol!)
            .Where(g => g.Count() > 1)
            .Select(g => g.Key)
            .ToList();
        Assert.Empty(duplicates);
    }

    [Fact]
    public void Enforcement_states_are_numeric_keys_with_unique_names()
    {
        foreach (var (key, state) in ErrorCodeCatalog.EnforcementStates)
        {
            Assert.Matches("^-?\\d+$", key);
            Assert.Equal(key, state.Value);
            Assert.False(string.IsNullOrWhiteSpace(state.Name));
            Assert.False(string.IsNullOrWhiteSpace(state.Description));
        }
        Assert.Equal(ErrorCodeCatalog.EnforcementStates.Count, ErrorCodeCatalog.EnforcementStates.Values.Select(s => s.Name).Distinct().Count());
    }

    [Fact]
    public void TryLookup_returns_null_for_null_or_empty()
    {
        Assert.Null(ErrorCodeCatalog.TryLookup(null));
        Assert.Null(ErrorCodeCatalog.TryLookup(""));
        Assert.Null(ErrorCodeCatalog.TryLookup("   "));
    }

    [Fact]
    public void TryLookup_returns_null_for_unknown_code()
    {
        Assert.Null(ErrorCodeCatalog.TryLookup("0xDEADBEEF"));
        Assert.Null(ErrorCodeCatalog.TryLookup("99999"));
        Assert.Null(ErrorCodeCatalog.TryLookup("not-a-code"));
    }

    [Fact]
    public void TryLookup_finds_lowercased_hex_direct()
    {
        var entry = ErrorCodeCatalog.TryLookup("0x80070005");
        Assert.NotNull(entry);
        Assert.Equal("Access is denied", entry!.Description);
        Assert.Equal(ErrorCodeConfidence.High, entry.Confidence);
        Assert.Equal("ERROR_ACCESS_DENIED", entry.Symbol);
        Assert.Equal("win32", entry.Category);
        Assert.True(entry.ImeRetriesDuringEsp, "Win32 error 5 is on the IME MSI retry list");
    }

    [Fact]
    public void TryLookup_normalises_uppercase_hex()
    {
        var entry = ErrorCodeCatalog.TryLookup("0X80070005");
        Assert.NotNull(entry);
        Assert.Equal("Access is denied", entry!.Description);
    }

    [Fact]
    public void TryLookup_normalises_short_hex_without_leading_zeros()
    {
        var entry = ErrorCodeCatalog.TryLookup("0x0000000080070005");
        Assert.NotNull(entry);
        Assert.Equal("Access is denied", entry!.Description);
    }

    [Fact]
    public void TryLookup_converts_signed_decimal_hresult_to_hex()
    {
        // -2147024891 (signed decimal) == 0x80070005 (unsigned hex)
        var entry = ErrorCodeCatalog.TryLookup("-2147024891");
        Assert.NotNull(entry);
        Assert.Equal("Access is denied", entry!.Description);
    }

    [Fact]
    public void TryLookup_finds_msi_decimal_exit_code()
    {
        var entry = ErrorCodeCatalog.TryLookup("1603");
        Assert.NotNull(entry);
        Assert.Contains("fatal error", entry!.Description);
        Assert.Equal("ERROR_INSTALL_FAILURE", entry.Symbol);
        Assert.Equal("msi", entry.Category);
    }

    [Fact]
    public void TryLookup_finds_intune_specific_code()
    {
        // Wording pinned in the generator: rule explanations and the web tests depend on it.
        var entry = ErrorCodeCatalog.TryLookup("0x87d1041c");
        Assert.NotNull(entry);
        Assert.Contains("Application not detected", entry!.Description);
        Assert.Equal(ErrorCodeConfidence.High, entry.Confidence);
        Assert.Equal("intune-win32", entry.Category);
    }

    [Fact]
    public void TryLookup_preserves_confidence_levels()
    {
        var high = ErrorCodeCatalog.TryLookup("0x80070005");
        var medium = ErrorCodeCatalog.TryLookup("0x87d30000");   // IME enum member paraphrase
        var low = ErrorCodeCatalog.TryLookup("0x87d00213");      // v1 entry without primary source

        Assert.Equal(ErrorCodeConfidence.High, high!.Confidence);
        Assert.Equal(ErrorCodeConfidence.Medium, medium!.Confidence);
        Assert.StartsWith("ime:", medium.Source);
        Assert.Equal(ErrorCodeConfidence.Low, low!.Confidence);
        Assert.Equal("legacy-catalog-v1", low.Source);
    }

    [Fact]
    public void Intune_detection_rule_codes_carry_the_ime_meaning()
    {
        // v1 glossed these two as download/size errors; the IME enum says detection-rule errors.
        Assert.Contains("unknown detection type", ErrorCodeCatalog.TryLookup("0x87d30004")!.Description);
        Assert.Contains("invalid detection value", ErrorCodeCatalog.TryLookup("0x87d30006")!.Description);
        Assert.Equal("UnzipError", ErrorCodeCatalog.TryLookup("0x87d30067")!.Symbol);
    }

    [Fact]
    public void Success_hresult_has_an_explicit_entry()
    {
        var entry = ErrorCodeCatalog.TryLookup("0x00000000");
        Assert.NotNull(entry);
        Assert.Equal("S_OK", entry!.Symbol);
        // The decimal "0" stays the MSI exit code; the two never merge.
        Assert.Equal("ERROR_SUCCESS", ErrorCodeCatalog.TryLookup("0")?.Symbol);
    }

    [Fact]
    public void TryLookupDetailed_derives_msi_exit_code_from_hresult_from_win32()
    {
        var result = ErrorCodeCatalog.TryLookupDetailed("0x80070643");

        Assert.NotNull(result);
        Assert.Equal("1603", result!.Key);
        Assert.Equal(1603, result.DerivedFromWin32);
        Assert.Equal("ERROR_INSTALL_FAILURE", result.Entry.Symbol);
        Assert.Null(ErrorCodeCatalog.All.GetValueOrDefault("0x80070643"));
    }

    [Fact]
    public void TryLookupDetailed_derives_from_signed_decimal_too()
    {
        // -2147023293 == 0x80070643
        var result = ErrorCodeCatalog.TryLookupDetailed("-2147023293");
        Assert.NotNull(result);
        Assert.Equal("1603", result!.Key);
        Assert.Equal(1603, result.DerivedFromWin32);
    }

    [Fact]
    public void TryLookupDetailed_never_derives_a_zero_low_word_to_success()
    {
        Assert.Null(ErrorCodeCatalog.TryLookupDetailed("0x80070000"));
    }

    [Fact]
    public void TryLookupDetailed_prefers_the_direct_entry_over_derivation()
    {
        var result = ErrorCodeCatalog.TryLookupDetailed("0x80070005");
        Assert.NotNull(result);
        Assert.Equal("0x80070005", result!.Key);
        Assert.Null(result.DerivedFromWin32);
    }

    [Fact]
    public void TryLookupDetailed_does_not_derive_outside_the_msi_range()
    {
        // 0x80070999 → 2457: no decimal entry, no Win32 entry → miss, not a bogus derivation.
        Assert.Null(ErrorCodeCatalog.TryLookupDetailed("0x80070999"));
    }

    [Fact]
    public void TryLookupBySymbol_resolves_symbols_case_insensitively()
    {
        var result = ErrorCodeCatalog.TryLookupBySymbol("ERROR_INSTALL_FAILURE");
        Assert.NotNull(result);
        Assert.Equal("1603", result!.Key);

        Assert.Equal("0x80240022", ErrorCodeCatalog.TryLookupBySymbol("wu_e_all_updates_failed")?.Key);
        Assert.Null(ErrorCodeCatalog.TryLookupBySymbol("NOT_A_SYMBOL"));
        Assert.Null(ErrorCodeCatalog.TryLookupBySymbol(null));
    }

    [Fact]
    public void TryLookupEnforcementState_resolves_value_and_name()
    {
        var byValue = ErrorCodeCatalog.TryLookupEnforcementState("1000");
        Assert.NotNull(byValue);
        Assert.Equal("Success", byValue!.Name);

        var byName = ErrorCodeCatalog.TryLookupEnforcementState("ErrorDownloadingContent");
        Assert.NotNull(byName);
        Assert.Equal("5003", byName!.Value);

        Assert.Equal("NotAttemptedDependencyWithFailure", ErrorCodeCatalog.TryLookupEnforcementState("6001")?.Name);
        Assert.Null(ErrorCodeCatalog.TryLookupEnforcementState("424242"));
        Assert.Null(ErrorCodeCatalog.TryLookupEnforcementState(""));
    }

    [Fact]
    public void Windows_update_symbols_the_agent_used_to_hardcode_are_present()
    {
        // WindowsUpdateTracker reads hresultSymbol from the catalog since the v2 catalog.
        Assert.Equal("WU_E_ALL_UPDATES_FAILED", ErrorCodeCatalog.TryLookup("0x80240022")!.Symbol);
        Assert.Equal("WU_E_UH_INSTALLERFAILURE", ErrorCodeCatalog.TryLookup("0x8024200B")!.Symbol);
        Assert.Equal("CBS_E_STORE_CORRUPTION", ErrorCodeCatalog.TryLookup("0x800F0831")!.Symbol);
        Assert.Equal("CBS_E_INSTALLERS_FAILED", ErrorCodeCatalog.TryLookup("0x800F0922")!.Symbol);
        Assert.Equal("PSFX_E_MISSING_PAYLOAD_FILE", ErrorCodeCatalog.TryLookup("0x800F0991")!.Symbol);
        Assert.Equal("ERROR_TIMEOUT", ErrorCodeCatalog.TryLookup("0x800705B4")!.Symbol);
    }

    [Fact]
    public void Codes_named_by_analysis_rules_are_present()
    {
        foreach (var code in new[]
                 {
                     "0x800705b4", "0x801c03ea", "0x81039001", "0x81039023", "0x81039024", "0x80070490",
                     "0x80180014", "0x80180018", "0xc1036501", "0x801c03f3", "0x80070774", "0x87d13b9c",
                     "0x80073d02", "0x80073cf0", "0x80073cf9", "0x80073cff", "0x80004005", "1601", "1653", "1641",
                 })
        {
            Assert.NotNull(ErrorCodeCatalog.TryLookup(code));
        }
    }

    [Fact]
    public void TryLookup_entries_have_source_attribution()
    {
        var entry = ErrorCodeCatalog.TryLookup("0x80070005");
        Assert.NotNull(entry);
        Assert.StartsWith("msdoc:https://learn.microsoft.com/", entry!.Source);
    }
}
