// Ratchet baseline for lib/__tests__/apiClient.guard.test.ts — per-file counts of the legacy
// call-site patterns on 2026-09-06. Only ever shrinks: a migrated file lowers or drops its entry,
// a new raw site anywhere fails the guard. Regenerate a shrunken map by hand, never by script over
// the whole tree (the guard's stale check tells you which entries to lower).

/** Files that keep a raw site for a stated reason; they never leave the baseline. */
export const PERMANENT: Record<string, string> = {
  "contexts/AuthContext.tsx": "auth/me bootstrap runs before the auth context exists — raw fetch by design",
  "components/landing/StatsBand.tsx": "unauthenticated public blob manifest, not the API",
  "app/health-check/page.tsx": "/version.json of the SWA itself, not the API",
  "app/settings/TenantConfigContext.tsx": "consent return path routes on TokenExpiredError (router.replace) — the one non-message handling",
};

export const AUTHENTICATEDFETCH_BASELINE: Record<string, number> = {
  "app/analyze-rules/page.tsx": 2,
  "app/annotations/page.tsx": 1,
  "app/apps/components/InventoryTab.tsx": 1,
  "app/apps/components/VulnerabilitiesTab.tsx": 1,
  "app/apps/detail/page.tsx": 2,
  "app/audit/page.tsx": 1,
  "app/dashboard/hooks/useBlockDevice.ts": 1,
  "app/dashboard/hooks/useDashboardSessions.ts": 3,
  "app/dashboard/hooks/useDashboardStats.ts": 1,
  "app/dashboard/hooks/useDeleteSession.ts": 3,
  "app/dashboard/hooks/useTenantList.ts": 1,
  "app/dashboard/page.tsx": 1,
  "app/delegations/accept/page.tsx": 2,
  "app/diagnosis/page.tsx": 3,
  "app/fleet-health/hooks/useFleetHealth.ts": 1,
  "app/fleet-health/page.tsx": 1,
  "app/fleet/hooks/useFleetSummaries.ts": 1,
  "app/gather-rules/page.tsx": 1,
  "app/geographic-performance/page.tsx": 1,
  "app/geographic-performance/sessions/page.tsx": 1,
  "app/health-check/page.tsx": 2,
  "app/progress/hooks/useProgressEvents.ts": 3,
  "app/progress/hooks/useProgressSearch.ts": 1,
  "app/sessions/components/AnalysisResultsSection.tsx": 1,
  "app/sessions/components/CollectLogsButton.tsx": 3,
  "app/sessions/components/DeviceHistoryBanner.tsx": 1,
  "app/sessions/components/SessionAnnotationsCard.tsx": 2,
  "app/sessions/hooks/useSessionAnalysis.ts": 2,
  "app/sessions/hooks/useSessionDetail.ts": 1,
  "app/sessions/hooks/useSessionEvents.ts": 2,
  "app/sessions/network-timeline/page.tsx": 2,
  "app/sessions/page.tsx": 5,
  "app/settings/TenantConfigContext.tsx": 20,
  "app/settings/components/HardwareRejectionInsights.tsx": 1,
  "app/settings/components/McpUsersSection.tsx": 8,
  "app/settings/components/NotRegisteredDevicesInsights.tsx": 1,
  "app/settings/components/OffboardingSection.tsx": 1,
  "app/settings/components/TpmIncompatibleDevicesInsights.tsx": 1,
  "app/settings/reporting/sections/SectionMcpUsage.tsx": 2,
  "app/settings/tenant/sections/SectionDelegatedAccess.tsx": 6,
  "app/settings/tenant/sections/SectionOptionalGraphCapabilities.tsx": 2,
  "app/settings/tenant/sections/SectionSubmitLogs.tsx": 1,
  "app/sla/page.tsx": 1,
  "app/usage-metrics/page.tsx": 1,
  "components/DelegatedSlotPrompt.tsx": 1,
  "components/FeedbackBubble.tsx": 3,
  "components/GlobalSearch.tsx": 1,
  "contexts/GlobalNotificationContext.tsx": 3,
  "contexts/SignalRContext.tsx": 3,
  "contexts/TenantNotificationContext.tsx": 3,
  "hooks/useDiagnosticsPathsCatalog.ts": 1,
  "hooks/useTenantList.ts": 1,
};

export const DEDUPEDAUTHFETCH_BASELINE: Record<string, number> = {
};

export const JSONPARSE_BASELINE: Record<string, number> = {
  "app/activation/page.tsx": 1,
  "app/analyze-rules/page.tsx": 2,
  "app/annotations/page.tsx": 1,
  "app/apps/components/InventoryTab.tsx": 1,
  "app/apps/components/VulnerabilitiesTab.tsx": 1,
  "app/apps/detail/page.tsx": 2,
  "app/audit/page.tsx": 1,
  "app/dashboard/hooks/deleteSessionResponse.ts": 1,
  "app/dashboard/hooks/useBlockDevice.ts": 1,
  "app/dashboard/hooks/useDashboardSessions.ts": 4,
  "app/dashboard/hooks/useDashboardStats.ts": 2,
  "app/dashboard/hooks/useTenantList.ts": 1,
  "app/dashboard/page.tsx": 1,
  "app/delegations/accept/page.tsx": 3,
  "app/diagnosis/page.tsx": 3,
  "app/fleet-health/hooks/useFleetHealth.ts": 2,
  "app/fleet-health/page.tsx": 1,
  "app/fleet/hooks/useFleetSummaries.ts": 1,
  "app/gather-rules/page.tsx": 1,
  "app/geographic-performance/page.tsx": 1,
  "app/geographic-performance/sessions/page.tsx": 1,
  "app/health-check/page.tsx": 3,
  "app/progress/hooks/useProgressEvents.ts": 3,
  "app/progress/hooks/useProgressSearch.ts": 1,
  "app/sessions/components/AnalysisResultsSection.tsx": 1,
  "app/sessions/components/CollectLogsButton.tsx": 1,
  "app/sessions/components/DeviceHistoryBanner.tsx": 1,
  "app/sessions/components/SessionAnnotationsCard.tsx": 2,
  "app/sessions/hooks/useSessionAnalysis.ts": 2,
  "app/sessions/hooks/useSessionDetail.ts": 1,
  "app/sessions/hooks/useSessionEvents.ts": 2,
  "app/sessions/network-timeline/page.tsx": 2,
  "app/sessions/page.tsx": 2,
  "app/settings/TenantConfigContext.tsx": 23,
  "app/settings/components/HardwareRejectionInsights.tsx": 1,
  "app/settings/components/McpUsersSection.tsx": 8,
  "app/settings/components/NotRegisteredDevicesInsights.tsx": 1,
  "app/settings/components/TpmIncompatibleDevicesInsights.tsx": 1,
  "app/settings/reporting/sections/SectionMcpUsage.tsx": 2,
  "app/settings/tenant/sections/SectionDelegatedAccess.tsx": 6,
  "app/settings/tenant/sections/SectionOptionalGraphCapabilities.tsx": 1,
  "app/settings/tenant/sections/SectionSubmitLogs.tsx": 1,
  "app/sla/page.tsx": 1,
  "app/usage-metrics/page.tsx": 1,
  "components/DelegatedSlotPrompt.tsx": 1,
  "components/FeedbackBubble.tsx": 1,
  "components/GlobalSearch.tsx": 1,
  "components/landing/StatsBand.tsx": 2,
  "contexts/AuthContext.tsx": 3,
  "contexts/GlobalNotificationContext.tsx": 1,
  "contexts/TenantNotificationContext.tsx": 1,
  "hooks/useDiagnosticsPathsCatalog.ts": 1,
  "hooks/useTenantList.ts": 1,
};

export const TOKENEXPIRED_BASELINE: Record<string, number> = {
  "app/admin/ops/session-cleanup/components/MaintenanceStatusBanner.tsx": 1,
  "app/apps/components/InventoryTab.tsx": 1,
  "app/apps/components/VulnerabilitiesTab.tsx": 1,
  "app/apps/detail/page.tsx": 2,
  "app/audit/page.tsx": 1,
  "app/dashboard/hooks/useBlockDevice.ts": 2,
  "app/dashboard/hooks/useDashboardSessions.ts": 3,
  "app/dashboard/hooks/useDashboardStats.ts": 1,
  "app/dashboard/hooks/useDeleteSession.ts": 2,
  "app/dashboard/hooks/useTenantSecurityConfig.ts": 1,
  "app/delegations/accept/page.tsx": 1,
  "app/diagnosis/page.tsx": 3,
  "app/fleet-health/hooks/useFleetHealth.ts": 1,
  "app/fleet-health/page.tsx": 1,
  "app/geographic-performance/page.tsx": 1,
  "app/geographic-performance/sessions/page.tsx": 1,
  "app/health-check/page.tsx": 1,
  "app/progress/hooks/useProgressEvents.ts": 1,
  "app/progress/hooks/useProgressSearch.ts": 1,
  "app/sessions/components/CollectLogsButton.tsx": 1,
  "app/sessions/components/SessionAnnotationsCard.tsx": 1,
  "app/sessions/hooks/useSessionDetail.ts": 1,
  "app/sessions/hooks/useSessionEvents.ts": 1,
  "app/sessions/page.tsx": 1,
  "app/settings/TenantConfigContext.tsx": 16,
  "app/settings/components/McpUsersSection.tsx": 6,
  "app/settings/components/OffboardingSection.tsx": 1,
  "app/settings/reporting/sections/SectionMcpUsage.tsx": 1,
  "app/settings/tenant/sections/SectionDelegatedAccess.tsx": 1,
  "app/settings/tenant/sections/SectionSubmitLogs.tsx": 1,
  "app/sla/page.tsx": 1,
  "app/usage-metrics/page.tsx": 1,
};
