/**
 * Wrapper around the shared error-codes catalog (schemaVersion 2).
 *
 * The catalog lives at `src/Shared/AutopilotMonitor.Shared/Resources/error-codes.json`
 * (generated by `scripts/error-codes/generate.mjs` at the repo root) and is synced into
 * `utils/error-codes.json` at build time (`scripts/sync-error-codes.js`, wired into the
 * `prebuild` npm script). The sync validates the catalog, shortens `source` to its kind and
 * drops the enforcement-state map; backend, MCP and web resolve from the same entries.
 *
 * Lookup mirrors the C# `ErrorCodeCatalog`: direct key, hex normalisation, signed-decimal
 * HRESULT, then the HRESULT_FROM_WIN32 derivation (`0x80070643` → `1603`, reported as
 * `derivedFromWin32`, never merged into the description).
 */

import catalogFile from "./error-codes.json";

/**
 * Confidence level for an error code mapping.
 *  - "high"   — taken from an MS Learn page or from the IME build named in `source`
 *  - "medium" — paraphrase of an enum member name or of an analysis rule
 *  - "low"    — carried over from the v1 catalog without a primary source
 */
export type ErrorCodeConfidence = "high" | "medium" | "low";

export const ERROR_CODE_CATEGORIES = [
  "msi", "win32", "com", "appx", "windows-update", "cbs", "intune-win32", "intune-mobile",
  "mdm-enrollment", "autopilot", "entra-join", "delivery-optimization",
] as const;
export type ErrorCodeCategory = (typeof ERROR_CODE_CATEGORIES)[number];

export interface ErrorCodeEntry {
  description: string;
  confidence: ErrorCodeConfidence;
  /** Provenance kind — `msdoc` (or `msdoc:<url>` from the backend), `ime:<version>`, `winerror.h`, `rule:<id>`, `legacy-catalog-v1`. */
  source: string;
  category: ErrorCodeCategory;
  /** `ERROR_INSTALL_FAILURE`, `WU_E_ALL_UPDATES_FAILED`, an IME enum member — absent for paraphrased rows. */
  symbol?: string;
  /** One of the MSI return codes the IME retries automatically during the Autopilot ESP. */
  imeRetriesDuringEsp?: boolean;
}

/**
 * Backend-enriched `*Info` sibling: the entry plus the derivation marker the enricher adds
 * when a `0x8007xxxx` value resolved through its low word to a decimal MSI entry.
 */
export interface ErrorCodeInfo extends ErrorCodeEntry {
  derivedFromWin32?: number;
}

export interface ErrorCodeLookup {
  entry: ErrorCodeEntry;
  /** Normalised catalog key that matched ("0x80070005", "1603"). */
  key: string;
  /** Set when the HRESULT_FROM_WIN32 derivation applied. */
  derivedFromWin32?: number;
}

interface CatalogFile {
  schemaVersion: number;
  entries: Record<string, ErrorCodeEntry>;
}

const typedCatalog = catalogFile as CatalogFile;

/**
 * Mapping of known Windows / MSI / Intune error codes to structured entries.
 * Keys are normalised lowercase hex strings (e.g. "0x80070005") or decimal strings (e.g. "1603").
 */
const errorCodeMap: Record<string, ErrorCodeEntry> = Object.fromEntries(
  Object.entries(typedCatalog.entries).map(([k, v]) => [k.toLowerCase(), v])
);

/** Look up a structured entry for a raw code; null when no mapping is found. */
function lookup(code: string | number | null | undefined): ErrorCodeLookup | null {
  if (code == null) return null;
  const raw = String(code).trim();
  if (raw === "") return null;

  // 1) Direct lookup (handles decimal keys like "1603" and already-lowered hex)
  const lowered = raw.toLowerCase();
  const direct = errorCodeMap[lowered];
  if (direct) return { entry: direct, key: lowered };

  // 2) Hex input normalisation ("0X..." → "0x...", strip leading zeros, repad to 8)
  let hexKey: string | null = null;
  if (/^0x/i.test(raw)) {
    const body = raw.slice(2).toLowerCase().replace(/^0+/, "") || "0";
    if (body.length <= 8) hexKey = "0x" + body.padStart(8, "0");
  } else {
    // 3) Signed-decimal HRESULT → unsigned hex  (e.g. -2147024891 → 0x80070005)
    const num = /^-\d+$/.test(raw) ? parseInt(raw, 10) : NaN;
    if (!isNaN(num) && num < 0 && num >= -2147483648) hexKey = "0x" + (num >>> 0).toString(16).padStart(8, "0");
  }
  if (!hexKey) return null;

  const hex = errorCodeMap[hexKey];
  if (hex) return { entry: hex, key: hexKey };

  // 4) HRESULT_FROM_WIN32 derivation: facility 7, no direct entry, low word ≠ 0, decimal entry present.
  if (hexKey.startsWith("0x8007")) {
    const low = parseInt(hexKey.slice(6), 16);
    if (low !== 0) {
      const decimalKey = String(low);
      const derived = errorCodeMap[decimalKey];
      if (derived) return { entry: derived, key: decimalKey, derivedFromWin32: low };
    }
  }
  return null;
}

/**
 * Look up a human-readable description for a Windows / MSI / Intune error code.
 *
 * Accepts:
 *  - Decimal strings:       "1603", "0"
 *  - Hex strings:           "0x80070005", "0X80070005"
 *  - Signed-decimal HRESULT: "-2147024891"  (converted to unsigned hex internally)
 *
 * Returns null when no mapping is found.
 */
export function getErrorCodeDescription(code: string | number | null | undefined): string | null {
  return lookup(code)?.entry.description ?? null;
}

/** Look up the full structured entry (description, confidence, source, category, symbol). */
export function getErrorCodeEntry(code: string | number | null | undefined): ErrorCodeEntry | null {
  return lookup(code)?.entry ?? null;
}

/** Look up the entry together with the matched key and the HRESULT_FROM_WIN32 derivation. */
export function getErrorCodeLookup(code: string | number | null | undefined): ErrorCodeLookup | null {
  return lookup(code);
}

/**
 * Backend-enriched info entry. The backend ErrorCodeEnricher injects sibling
 * `{codeKey}Info` properties into event Data with the shape of `ErrorCodeInfo`. When
 * present we prefer the server-side value (authoritative catalog version), and only fall
 * back to the local lookup for older responses that don't carry the enrichment yet.
 */
export function getEnrichedOrLookup(
  info: ErrorCodeInfo | null | undefined,
  code: string | number | null | undefined
): ErrorCodeEntry | null {
  if (info && typeof info === "object" && typeof info.description === "string") {
    return info;
  }
  return getErrorCodeEntry(code);
}

/**
 * Human wording for an entry's provenance token — the raw token (URL, build number,
 * rule id) is never shown as-is. Accepts both the web copy's short kind ("msdoc") and the
 * backend's full token ("msdoc:https://…").
 */
export function formatErrorCodeSource(source: string | null | undefined): string {
  const s = (source ?? "").trim();
  if (s === "msdoc" || s.startsWith("msdoc:")) return "Microsoft Learn";
  if (s.startsWith("ime:")) return `Intune Management Extension ${s.slice(4)}`;
  if (s === "winerror.h") return "winerror.h";
  if (s.startsWith("rule:")) return `Analysis rule ${s.slice(5)}`;
  if (s === "legacy-catalog-v1") return "Community";
  return s || "Unknown source";
}

/** Tooltip text for a resolved entry: provenance plus confidence. */
export function errorCodeTooltip(entry: Pick<ErrorCodeEntry, "source" | "confidence">): string {
  return `${formatErrorCodeSource(entry.source)} (${entry.confidence} confidence)`;
}

/**
 * Format a raw numeric error code for display.
 * Signed-decimal HRESULTs are converted to hex notation.
 * Decimal exit codes stay as-is.
 */
export function formatErrorCode(code: string | number): string {
  const raw = String(code).trim();
  const num = parseInt(raw, 10);

  // Already hex
  if (/^0x/i.test(raw)) return raw.toUpperCase();

  // Negative signed-decimal → hex
  if (!isNaN(num) && num < 0) {
    return "0x" + (num >>> 0).toString(16).toUpperCase();
  }

  // Positive decimal (exit code) — keep as-is
  return raw;
}
