using System;
using AutopilotMonitor.Functions.Security;
using AutopilotMonitor.Shared;

namespace AutopilotMonitor.Functions.Functions.Bootstrap
{
    /// <summary>
    /// Generates the OOBE bootstrap PowerShell script served at /api/bootstrap/go/{code}
    /// (customer-facing: irm https://go.autopilotmonitor.com/{code} | iex).
    /// Ported 1:1 from the portal's app/go/[code]/route.ts when the endpoint moved into
    /// the backend for the static-export migration.
    /// </summary>
    public static class OobeBootstrapScriptGenerator
    {
        /// <summary>
        /// Hard cap on error messages embedded in the generated PS script. Defense
        /// against an upstream bug or compromise emitting a huge message that would
        /// otherwise be inlined verbatim into the script body.
        /// </summary>
        internal const int MaxErrorMessageLength = 200;

        /// <summary>
        /// Builds the always-HTTP-200 error script: irm | iex executes it and the
        /// Write-Host surfaces the message on the OOBE console.
        /// </summary>
        public static string GenerateErrorScript(string message)
        {
            // Cap length BEFORE quote-escaping so the cap is on raw input, not the
            // post-escape size (which can double for '-heavy strings).
            var truncated = message.Length > MaxErrorMessageLength
                ? message.Substring(0, MaxErrorMessageLength) + "..."
                : message;
            var safeMsg = truncated.Replace("'", "''");
            return $"Write-Host ''; Write-Host 'ERROR: {safeMsg}' -ForegroundColor Red; Write-Host ''";
        }

        // SECURITY INVARIANT: All template parameters MUST come from
        // BootstrapScriptValueValidator.TryValidate. The single-quoted PowerShell
        // string literals below are the second line of defense against injection
        // (single-quoted PS strings do NOT expand $(...), $var, or backticks).
        // Do NOT change to double-quoted without re-reviewing the validator's
        // character classes end-to-end.
        //
        // The template is a raw string with __TOKEN__ placeholders substituted via
        // Replace — deliberately NOT string interpolation or string.Format, because
        // the script body is full of PowerShell $vars and {braces}.
        public static string GenerateSuccessScript(
            BootstrapScriptValueValidator.ValidatedValues values,
            DateTime generatedAtUtc)
        {
            // "yyyy-MM-ddTHH:mm:ss.fffZ" — byte parity with JS toISOString(), which the
            // previous portal implementation used for both timestamps. Inputs are UTC by
            // contract; no ToUniversalTime() — it would shift Unspecified-kind values
            // (e.g. from table storage) by the server's local offset.
            var generatedAt = generatedAtUtc.ToString("yyyy-MM-ddTHH:mm:ss.fff'Z'");
            var expiresAt = values.ExpiresAtUtc.ToString("yyyy-MM-ddTHH:mm:ss.fff'Z'");

            return Template
                .Replace("__GENERATED_AT__", generatedAt)
                .Replace("__EXPIRES_AT__", expiresAt)
                .Replace("__AGENT_DOWNLOAD_URL__", values.AgentDownloadUrl)
                .Replace("__BOOTSTRAP_TOKEN__", values.Token)
                .Replace("__TENANT_ID__", values.TenantId)
                .Replace("__PORTAL_URL__", Constants.PortalBaseUrl);
        }

        private const string Template = """
#Requires -RunAsAdministrator
<#
.SYNOPSIS
    Autopilot Monitor OOBE Bootstrap
    Generated: __GENERATED_AT__
    Expires:   __EXPIRES_AT__

    This script was generated by the Autopilot Monitor platform.
    It installs the monitoring agent before Intune enrollment begins,
    enabling full session capture from the start of OOBE.
#>

$ErrorActionPreference = "Stop"

$AgentDownloadUrl = '__AGENT_DOWNLOAD_URL__'
$AgentBasePath    = "$env:ProgramData\AutopilotMonitor"
$AgentBinPath     = "$AgentBasePath\Agent"
$AgentLogPath     = "$AgentBasePath\Logs"
$LogFile          = "$AgentLogPath\oobe_bootstrap.log"

# Create directories
New-Item -Path $AgentBasePath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
New-Item -Path $AgentBinPath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null
New-Item -Path $AgentLogPath -ItemType Directory -Force -ErrorAction SilentlyContinue | Out-Null

function Write-Log {
    param([string]$Message)
    $timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $logMessage = "[$timestamp] $Message"
    Write-Host $logMessage
    Add-Content -Path $LogFile -Value $logMessage -ErrorAction SilentlyContinue
}

try {
    Write-Log "===== Autopilot Monitor OOBE Bootstrap ====="
    Write-Log 'Bootstrap token expires: __EXPIRES_AT__'

    # Check if agent is already installed
    $agentExePath = Join-Path $AgentBinPath "AutopilotMonitor.Agent.exe"
    if (Test-Path $agentExePath) {
        Write-Log "Agent already installed at $agentExePath -- skipping download"
    }
    else {
        # Download agent ZIP
        $zipPath = Join-Path $env:TEMP "AutopilotMonitor-Agent.zip"
        Write-Log "Downloading agent from $AgentDownloadUrl..."

        $maxDownloadAttempts = 3
        $downloadAttempt = 0

        do {
            $downloadAttempt++
            try {
                Write-Log "Download attempt $downloadAttempt/$maxDownloadAttempts"
                Invoke-WebRequest -Uri $AgentDownloadUrl -OutFile $zipPath -UseBasicParsing -TimeoutSec 60 -ErrorAction Stop
                Write-Log "Downloaded agent to $zipPath"
                break
            }
            catch {
                if ($downloadAttempt -ge $maxDownloadAttempts) { throw }
                $retryDelays = @(2, 4, 8)
                $delay = $retryDelays[$downloadAttempt - 1]
                Write-Log "Download failed (attempt $downloadAttempt): $($_.Exception.Message). Retrying in ${delay}s..."
                Start-Sleep -Seconds $delay
            }
        } while ($downloadAttempt -lt $maxDownloadAttempts)

        # Extract
        Expand-Archive -Path $zipPath -DestinationPath $AgentBinPath -Force
        Remove-Item $zipPath -Force -ErrorAction SilentlyContinue
        Write-Log "Extracted agent to $AgentBinPath"

        if (-not (Test-Path $agentExePath)) {
            throw "Agent executable not found after extraction at $agentExePath"
        }
    }

    # Install agent with bootstrap token
    Write-Log "Installing agent with bootstrap token..."
    & $agentExePath --install --no-auth --bootstrap-token '__BOOTSTRAP_TOKEN__' --tenant-id '__TENANT_ID__'
    $installExitCode = $LASTEXITCODE
    if ($installExitCode -ne 0) {
        throw "Agent install failed with exit code $installExitCode"
    }

    Write-Log "===== OOBE Bootstrap Complete ====="
    Write-Log "Agent is now monitoring. View progress at __PORTAL_URL__"
    Write-Log ""
    Write-Log "The agent will:"
    Write-Log "  - Monitor enrollment from the very start"
    Write-Log "  - Switch to certificate auth after Intune enrollment"
    Write-Log "  - Self-destruct when enrollment completes"

    Write-Host ""
    Write-Host "Autopilot Monitor agent installed successfully!" -ForegroundColor Green
    Write-Host "View enrollment progress at __PORTAL_URL__" -ForegroundColor Cyan
    Write-Host ""
}
catch {
    Write-Log "===== OOBE Bootstrap FAILED ====="
    Write-Log "ERROR: $($_.Exception.Message)"
    Write-Log "Stack trace: $($_.ScriptStackTrace)"
    Write-Host ""
    Write-Host "ERROR: $($_.Exception.Message)" -ForegroundColor Red
    Write-Host "Check log file: $LogFile" -ForegroundColor Yellow
    Write-Host ""
    exit 1
}

""";
    }
}
